import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, Circle } from "lucide-react";
import { FaInstagram, FaLinkedinIn } from "react-icons/fa";
import { Navigation } from "@/components/Navigation";
import { SectionHeading } from "@/components/SectionHeading";
import { SignalProcess } from "@/components/SignalProcess";
import { Ecosystem } from "@/components/Ecosystem";
import { Footer } from "@/components/Footer";
import { SignalField } from "@/components/SignalField";
import { casebookTopics, method, socialLinks } from "@/content/site";
import { signalSmithDescription, signalSmithModel, signalSmithPhilosophy } from "@/content/brand";

export default function Home() {
  const organizationJsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "SignalSmith",
    url: "https://signalsmith.online/",
    logo: "https://signalsmith.online/assets/signalsmith-icon.svg",
    description: signalSmithDescription,
    sameAs: socialLinks.map(({ href }) => href),
  };

  return <><main id="top" className="overflow-hidden">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }} />
    <section className="relative min-h-[720px] bg-[var(--ink)] text-white md:min-h-[820px]">
      <Navigation /><div className="hero-grid absolute inset-0 z-0 opacity-40" aria-hidden="true" /><SignalField /><div className="absolute right-[-7rem] top-28 z-0 h-[28rem] w-[28rem] rounded-full border border-white/10 md:right-[-2rem] md:top-16" aria-hidden="true" /><div className="absolute bottom-0 left-0 z-0 h-px w-1/3 signal-line" aria-hidden="true" />
      <div className="relative z-10 mx-auto flex max-w-[1440px] flex-col justify-between px-6 pb-16 pt-36 md:min-h-[820px] md:px-10 md:pb-20 lg:px-14"><div className="max-w-full"><p className="eyebrow fade-up text-[var(--cyan)]">SignalSmith / Business Problems × Data</p><h1 className="display fade-up delay-1 mt-7 max-w-full font-medium">Start with<br /><span className="text-white/45">the problem.</span><br /><span className="text-[var(--cyan)]">Find the signal<span className="display-punctuation">.</span></span></h1><p className="fade-up delay-2 mt-10 max-w-xl text-lg leading-8 text-white/65 md:text-xl">{signalSmithDescription}</p></div>
        <div className="mt-24 grid gap-10 md:grid-cols-[1fr_2fr] md:items-end"><div className="flex items-center gap-3 cta text-white/45"><ArrowDown size={15} className="text-[var(--cyan)]" /> Start with the problem</div><div className="border-t border-white/20 pt-5"><div className="flex flex-wrap items-center gap-4 cta text-white/65 md:gap-6"><span className="text-white">Raw material</span><span className="text-[var(--cyan)]">→</span><span>Craft</span><span className="text-[var(--pink)]">→</span><span>Signal</span><span className="text-[var(--orange)]">→</span><span>Decision</span></div><p className="mt-5 max-w-xl text-sm leading-6 text-white/45">The work begins with the question, the context, and the decision that matters.</p></div></div>
      </div>
    </section>

    <section className="bg-[var(--paper)] px-6 py-24 md:px-10 md:py-32 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="grid gap-16 lg:grid-cols-[.65fr_1.30fr]"><SectionHeading eyebrow="The problem" title="Businesses don't just have a data problem." body="They have a problem knowing what matters." /><div className="grid-paper border border-black/10 p-5 md:p-8"><div className="mb-10 flex items-center justify-between"><span className="eyebrow">The SignalSmith mental model</span><Circle size={10} fill="currentColor" /></div><SignalProcess /></div></div></div></section>

    <section id="casebook" className="bg-white px-6 py-24 md:px-10 md:py-32 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow="01 / Learn / Casebook" title="Real business problems. Worked from first principles." body="The Casebook follows the entire chain — from the business question to the decision." /><Link href="/casebook" data-analytics-event="casebook_click" data-case-study="casebook" data-location="homepage" className="group cta inline-flex shrink-0 items-center gap-3 border-b border-black/30 pb-3 hover:border-black">Explore the Casebook <ArrowRight size={16} className="transition-transform group-hover:translate-x-1" /></Link></div><div className="mt-16 grid gap-5 md:grid-cols-3">{casebookTopics.map(([number, title, body]) => <Link key={title} href="/casebook" data-analytics-event="casebook_click" data-case-study={title} data-location="homepage" className="group relative min-h-[330px] border border-black/15 bg-[var(--paper)] p-6 transition-transform hover:-translate-y-1 md:p-8"><div className="flex justify-between"><span className="eyebrow">Casebook / {number}</span><ArrowUpRight size={18} strokeWidth={1.5} /></div><div className="absolute inset-x-6 bottom-7 md:inset-x-8"><div className="mb-5 h-px w-10 signal-line" /><h3 className="max-w-xs text-3xl font-medium tracking-[-.035em]">{title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-black/55">{body}</p></div></Link>)}</div></div></section>

    <section className="relative bg-[var(--ink)] px-6 py-24 text-white md:px-10 md:py-32 lg:px-14"><SignalField /><div className="relative z-10 mx-auto max-w-[1440px]"><SectionHeading light eyebrow="02 / Method" title="A way of thinking, not a collection of technologies." body={`${signalSmithPhilosophy} ${signalSmithModel}. Move from question to action. Each step earns its place by reducing uncertainty.`} /><div className="mt-16 grid border-t border-white/15 md:grid-cols-3 lg:grid-cols-6">{method.map(([num, name, desc]) => <div key={num} className="border-b border-r border-white/15 p-5 first:border-l md:min-h-[180px] md:p-6"><span className="eyebrow text-[var(--cyan)]">{num}</span><h3 className="mt-8 text-xl font-medium tracking-tight">{name}</h3><p className="mt-3 text-sm leading-6 text-white/45">{desc}</p></div>)}</div></div></section>

    <section id="ecosystem" className="bg-[var(--paper)] px-6 py-24 md:px-10 md:py-32 lg:px-14"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="03 / The SignalSmith ecosystem" title="A body of knowledge, not a single format." body="Everything remains SignalSmith. These names describe different ways of discovering problems, understanding them, solving them, and practicing the craft." /><div className="grid-paper flex items-end border-l border-black/10 p-8"><div><p className="eyebrow">Explore · Learn · Apply</p><p className="mt-5 max-w-md text-2xl font-medium leading-snug tracking-[-.04em]">One method. Many ways to work with it.</p></div></div></div><Ecosystem /></div></section>

    <section className="relative bg-[#e9ece8] px-6 py-24 md:px-10 md:py-32 lg:px-14"><div className="absolute right-0 top-0 h-full w-1/3 bg-[linear-gradient(135deg,transparent_49.5%,rgba(24,185,220,.16)_50%,transparent_50.5%)] opacity-50" aria-hidden="true" /><div className="relative mx-auto grid max-w-[1440px] gap-14 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="eyebrow">04 / Foundry</p><h2 className="section-title mt-5 max-w-3xl font-medium">Bring us the problem.<br /><span className="text-black/35">We'll find the signal.</span></h2><p className="mt-8 max-w-lg text-base leading-7 text-black/60">Foundry is SignalSmith's public laboratory for real-world problems — messy questions that deserve to be structured, investigated, and understood.</p></div><div className="border-t border-black/20 pt-5"><p className="eyebrow">Coming soon</p><p className="mt-5 text-lg leading-7">Problems enter. The craft begins. Useful knowledge comes out.</p><Link href="/foundry" data-analytics-event="foundry_click" data-location="homepage" className="cta mt-8 inline-flex items-center gap-3">Enter the Foundry <ArrowUpRight size={16} /></Link></div></div></section>

    <section id="connect" className="bg-white px-6 py-24 md:px-10 md:py-28 lg:px-14"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-12 md:flex-row md:items-end"><div><p className="eyebrow">05 / Connect</p><h2 className="section-title mt-5 max-w-2xl font-medium">Follow the work<br /><span className="text-black/35">as it takes shape.</span></h2></div><div className="max-w-sm"><p className="text-sm leading-6 text-black/55">One problem. One investigation. One useful signal at a time.</p><a href="mailto:contact@signalsmith.online" data-analytics-event="contact_click" data-location="connect" className="cta mt-8 inline-flex items-center gap-3 border-b border-black/30 pb-3">contact@signalsmith.online <ArrowUpRight size={15} /></a><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3">{socialLinks.map(({ name, platform, href }) => { const Icon = name === "Instagram" ? FaInstagram : FaLinkedinIn; return <a key={name} href={href} target="_blank" rel="noopener noreferrer" data-analytics-event="social_click" data-platform={platform} data-location="connect" data-analytics-external="true" aria-label={`SignalSmith on ${name}`} className="cta group inline-flex items-center gap-2 text-black/50 transition-colors hover:text-[var(--cyan)] focus-visible:text-[var(--cyan)]"><Icon size={15} aria-hidden="true" />{name}<ArrowUpRight size={13} className="transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" aria-hidden="true" /></a>; })}</div></div></div></section>
  </main><Footer /></>;
}
